# Generated by Django 4.1.7 on 2023-02-20 18:41

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='emoji',
            field=models.CharField(default='✋', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
