# Generated by Django 4.1.7 on 2023-02-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_player_created_date_player_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
